version: "3"

services:
  scooter_server:
    container_name: scooter_server
    build:
      context: scooter_server
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file:
      - .env

  scooter_client:
    build:
      context: scooter_client
      dockerfile: Dockerfile
    depends_on:
      - "scooter_server"
    ports:
        - "5000"
    env_file:
      - .env